// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package gttelemetry

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type GranTurismoTelemetry struct {
	Header *GranTurismoTelemetry_Header
	MapPositionCoordinates *GranTurismoTelemetry_Coordinate
	VelocityVector *GranTurismoTelemetry_Vector
	RotationalEnvelope *GranTurismoTelemetry_RotationalEnvelope
	Heading float32
	AngularVelocityVector *GranTurismoTelemetry_Vector
	RideHeight float32
	EngineRpm float32
	Oiv float32
	FuelLevel float32
	FuelCapacity float32
	GroundSpeed float32
	ManifoldPressure float32
	OilPressure float32
	WaterTemperature float32
	OilTemperature float32
	TyreTemperature *GranTurismoTelemetry_CornerSet
	SequenceId uint32
	CurrentLap uint16
	RaceLaps uint16
	BestLaptime int32
	LastLaptime int32
	TimeOfDay uint32
	StartingPosition int16
	RaceEntrants int16
	RevLightRpmMin uint16
	RevLightRpmMax uint16
	CalculatedMaxSpeed uint16
	Flags *GranTurismoTelemetry_Flags
	TransmissionGear *GranTurismoTelemetry_TransmissionGear
	Throttle uint8
	Brake uint8
	Ignore1 []byte
	RoadPlaneVector *GranTurismoTelemetry_Vector
	RoadPlaneDistance uint32
	WheelRadiansPerSecond *GranTurismoTelemetry_CornerSet
	TyreRadius *GranTurismoTelemetry_CornerSet
	SuspensionHeight *GranTurismoTelemetry_CornerSet
	Reserved []byte
	ClutchActuation float32
	ClutchEngagement float32
	CluchOutputRpm float32
	TransmissionTopSpeedRatio float32
	TransmissionGearRatio *GranTurismoTelemetry_GearRatio
	VehicleId uint32
	SteeringWheelAngleRadians float32
	SteeringWheelForceFeedback float32
	TranslationalEnvelope *GranTurismoTelemetry_TranslationalEnvelope
	ThrottleRaw uint8
	BrakeRaw uint8
	Unknown0x13e uint8
	Unknown0x13f uint8
	Unknown0x140 float32
	Unknown0x144 float32
	Unknown0x148 float32
	Unknown0x14c float32
	EnergyRecovery float32
	Unknown0x154 float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent interface{}
	_f_hasSectionTilde bool
	hasSectionTilde bool
	_f_headerIsGt7 bool
	headerIsGt7 bool
	_f_packetSize bool
	packetSize int
	_f_headerIsGt6 bool
	headerIsGt6 bool
	_f_hasSectionA bool
	hasSectionA bool
	_f_hasSectionB bool
	hasSectionB bool
}
func NewGranTurismoTelemetry() *GranTurismoTelemetry {
	return &GranTurismoTelemetry{
	}
}

func (this *GranTurismoTelemetry) Read(io *kaitai.Stream, parent interface{}, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewGranTurismoTelemetry_Header()
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	tmp2 := NewGranTurismoTelemetry_Coordinate()
	err = tmp2.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.MapPositionCoordinates = tmp2
	tmp3 := NewGranTurismoTelemetry_Vector()
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.VelocityVector = tmp3
	tmp4 := NewGranTurismoTelemetry_RotationalEnvelope()
	err = tmp4.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.RotationalEnvelope = tmp4
	tmp5, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Heading = float32(tmp5)
	tmp6 := NewGranTurismoTelemetry_Vector()
	err = tmp6.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AngularVelocityVector = tmp6
	tmp7, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.RideHeight = float32(tmp7)
	tmp8, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.EngineRpm = float32(tmp8)
	tmp9, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Oiv = float32(tmp9)
	tmp10, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.FuelLevel = float32(tmp10)
	tmp11, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.FuelCapacity = float32(tmp11)
	tmp12, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.GroundSpeed = float32(tmp12)
	tmp13, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.ManifoldPressure = float32(tmp13)
	tmp14, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.OilPressure = float32(tmp14)
	tmp15, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.WaterTemperature = float32(tmp15)
	tmp16, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.OilTemperature = float32(tmp16)
	tmp17 := NewGranTurismoTelemetry_CornerSet()
	err = tmp17.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TyreTemperature = tmp17
	tmp18, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SequenceId = uint32(tmp18)
	tmp19, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CurrentLap = uint16(tmp19)
	tmp20, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RaceLaps = uint16(tmp20)
	tmp21, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.BestLaptime = int32(tmp21)
	tmp22, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.LastLaptime = int32(tmp22)
	tmp23, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeOfDay = uint32(tmp23)
	tmp24, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.StartingPosition = int16(tmp24)
	tmp25, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.RaceEntrants = int16(tmp25)
	tmp26, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RevLightRpmMin = uint16(tmp26)
	tmp27, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.RevLightRpmMax = uint16(tmp27)
	tmp28, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.CalculatedMaxSpeed = uint16(tmp28)
	tmp29 := NewGranTurismoTelemetry_Flags()
	err = tmp29.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp29
	tmp30 := NewGranTurismoTelemetry_TransmissionGear()
	err = tmp30.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TransmissionGear = tmp30
	tmp31, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Throttle = tmp31
	tmp32, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Brake = tmp32
	tmp33, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp33 = tmp33
	this.Ignore1 = tmp33
	tmp34 := NewGranTurismoTelemetry_Vector()
	err = tmp34.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.RoadPlaneVector = tmp34
	tmp35, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.RoadPlaneDistance = uint32(tmp35)
	tmp36 := NewGranTurismoTelemetry_CornerSet()
	err = tmp36.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.WheelRadiansPerSecond = tmp36
	tmp37 := NewGranTurismoTelemetry_CornerSet()
	err = tmp37.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TyreRadius = tmp37
	tmp38 := NewGranTurismoTelemetry_CornerSet()
	err = tmp38.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.SuspensionHeight = tmp38
	tmp39, err := this._io.ReadBytes(int(32))
	if err != nil {
		return err
	}
	tmp39 = tmp39
	this.Reserved = tmp39
	tmp40, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.ClutchActuation = float32(tmp40)
	tmp41, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.ClutchEngagement = float32(tmp41)
	tmp42, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.CluchOutputRpm = float32(tmp42)
	tmp43, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.TransmissionTopSpeedRatio = float32(tmp43)
	tmp44 := NewGranTurismoTelemetry_GearRatio()
	err = tmp44.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TransmissionGearRatio = tmp44
	tmp45, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.VehicleId = uint32(tmp45)
	tmp46, err := this.HasSectionB()
	if err != nil {
		return err
	}
	if (tmp46) {
		tmp47, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.SteeringWheelAngleRadians = float32(tmp47)
	}
	tmp48, err := this.HasSectionB()
	if err != nil {
		return err
	}
	if (tmp48) {
		tmp49, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.SteeringWheelForceFeedback = float32(tmp49)
	}
	tmp50, err := this.HasSectionB()
	if err != nil {
		return err
	}
	if (tmp50) {
		tmp51 := NewGranTurismoTelemetry_TranslationalEnvelope()
		err = tmp51.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.TranslationalEnvelope = tmp51
	}
	tmp52, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp52) {
		tmp53, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.ThrottleRaw = tmp53
	}
	tmp54, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp54) {
		tmp55, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.BrakeRaw = tmp55
	}
	tmp56, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp56) {
		tmp57, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown0x13e = tmp57
	}
	tmp58, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp58) {
		tmp59, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Unknown0x13f = tmp59
	}
	tmp60, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp60) {
		tmp61, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Unknown0x140 = float32(tmp61)
	}
	tmp62, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp62) {
		tmp63, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Unknown0x144 = float32(tmp63)
	}
	tmp64, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp64) {
		tmp65, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Unknown0x148 = float32(tmp65)
	}
	tmp66, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp66) {
		tmp67, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Unknown0x14c = float32(tmp67)
	}
	tmp68, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp68) {
		tmp69, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.EnergyRecovery = float32(tmp69)
	}
	tmp70, err := this.HasSectionTilde()
	if err != nil {
		return err
	}
	if (tmp70) {
		tmp71, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Unknown0x154 = float32(tmp71)
	}
	return err
}

/**
 * True when the telemetry data contains data requested with format "~"
 */
func (this *GranTurismoTelemetry) HasSectionTilde() (v bool, err error) {
	if (this._f_hasSectionTilde) {
		return this.hasSectionTilde, nil
	}
	tmp72, err := this._io.Size()
	if err != nil {
		return false, err
	}
	this.hasSectionTilde = bool(tmp72 > 316)
	this._f_hasSectionTilde = true
	return this.hasSectionTilde, nil
}

/**
 * True when the telemetry data is sent from Gran Turismo 7 or Sport
 */
func (this *GranTurismoTelemetry) HeaderIsGt7() (v bool, err error) {
	if (this._f_headerIsGt7) {
		return this.headerIsGt7, nil
	}
	this.headerIsGt7 = bool(this.Header.Magic == 1194808112)
	this._f_headerIsGt7 = true
	return this.headerIsGt7, nil
}

/**
 * The total size in bytes of the telemetry packet
 */
func (this *GranTurismoTelemetry) PacketSize() (v int, err error) {
	if (this._f_packetSize) {
		return this.packetSize, nil
	}
	tmp73, err := this._io.Size()
	if err != nil {
		return 0, err
	}
	this.packetSize = int(tmp73)
	this._f_packetSize = true
	return this.packetSize, nil
}

/**
 * True when the telemetry data is sent from Gran Turismo 6
 */
func (this *GranTurismoTelemetry) HeaderIsGt6() (v bool, err error) {
	if (this._f_headerIsGt6) {
		return this.headerIsGt6, nil
	}
	this.headerIsGt6 = bool(this.Header.Magic == 810760007)
	this._f_headerIsGt6 = true
	return this.headerIsGt6, nil
}

/**
 * True when the telemetry data contains data requested with format "A"
 */
func (this *GranTurismoTelemetry) HasSectionA() (v bool, err error) {
	if (this._f_hasSectionA) {
		return this.hasSectionA, nil
	}
	tmp74, err := this._io.Size()
	if err != nil {
		return false, err
	}
	this.hasSectionA = bool(tmp74 >= 296)
	this._f_hasSectionA = true
	return this.hasSectionA, nil
}

/**
 * True when the telemetry data contains data requested with format "B"
 */
func (this *GranTurismoTelemetry) HasSectionB() (v bool, err error) {
	if (this._f_hasSectionB) {
		return this.hasSectionB, nil
	}
	tmp75, err := this._io.Size()
	if err != nil {
		return false, err
	}
	this.hasSectionB = bool(tmp75 > 296)
	this._f_hasSectionB = true
	return this.hasSectionB, nil
}

/**
 * Various flags for the current state of play and instrument cluster indicators
 */
type GranTurismoTelemetry_Flags struct {
	Live bool
	GamePaused bool
	Loading bool
	InGear bool
	HasTurbo bool
	RevLimiterAlert bool
	HandBrakeActive bool
	HeadlightsActive bool
	HighBeamActive bool
	LowBeamActive bool
	AsmActive bool
	TcsActive bool
	Flag13 bool
	Flag14 bool
	Flag15 bool
	Flag16 bool
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_Flags() *GranTurismoTelemetry_Flags {
	return &GranTurismoTelemetry_Flags{
	}
}

func (this *GranTurismoTelemetry_Flags) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp76, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Live = tmp76 != 0
	tmp77, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.GamePaused = tmp77 != 0
	tmp78, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Loading = tmp78 != 0
	tmp79, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.InGear = tmp79 != 0
	tmp80, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HasTurbo = tmp80 != 0
	tmp81, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.RevLimiterAlert = tmp81 != 0
	tmp82, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HandBrakeActive = tmp82 != 0
	tmp83, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HeadlightsActive = tmp83 != 0
	tmp84, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.HighBeamActive = tmp84 != 0
	tmp85, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.LowBeamActive = tmp85 != 0
	tmp86, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.AsmActive = tmp86 != 0
	tmp87, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.TcsActive = tmp87 != 0
	tmp88, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Flag13 = tmp88 != 0
	tmp89, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Flag14 = tmp89 != 0
	tmp90, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Flag15 = tmp90 != 0
	tmp91, err := this._io.ReadBitsIntLe(1)
	if err != nil {
		return err
	}
	this.Flag16 = tmp91 != 0
	return err
}

/**
 * 3D direction vector
 */
type GranTurismoTelemetry_Vector struct {
	VectorX float32
	VectorY float32
	VectorZ float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_Vector() *GranTurismoTelemetry_Vector {
	return &GranTurismoTelemetry_Vector{
	}
}

func (this *GranTurismoTelemetry_Vector) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp92, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.VectorX = float32(tmp92)
	tmp93, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.VectorY = float32(tmp93)
	tmp94, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.VectorZ = float32(tmp94)
	return err
}

/**
 * 6DOF translational envelope
 */
type GranTurismoTelemetry_TranslationalEnvelope struct {
	Sway float32
	Heave float32
	Surge float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_TranslationalEnvelope() *GranTurismoTelemetry_TranslationalEnvelope {
	return &GranTurismoTelemetry_TranslationalEnvelope{
	}
}

func (this *GranTurismoTelemetry_TranslationalEnvelope) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp95, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Sway = float32(tmp95)
	tmp96, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Heave = float32(tmp96)
	tmp97, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Surge = float32(tmp97)
	return err
}

/**
 * Data set representing each wheel or suspension component at the corners of the vehicle
 */
type GranTurismoTelemetry_CornerSet struct {
	FrontLeft float32
	FrontRight float32
	RearLeft float32
	RearRight float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_CornerSet() *GranTurismoTelemetry_CornerSet {
	return &GranTurismoTelemetry_CornerSet{
	}
}

func (this *GranTurismoTelemetry_CornerSet) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp98, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.FrontLeft = float32(tmp98)
	tmp99, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.FrontRight = float32(tmp99)
	tmp100, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.RearLeft = float32(tmp100)
	tmp101, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.RearRight = float32(tmp101)
	return err
}

/**
 * 3D position coordinates
 */
type GranTurismoTelemetry_Coordinate struct {
	CoordinateX float32
	CoordinateY float32
	CoordinateZ float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_Coordinate() *GranTurismoTelemetry_Coordinate {
	return &GranTurismoTelemetry_Coordinate{
	}
}

func (this *GranTurismoTelemetry_Coordinate) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp102, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.CoordinateX = float32(tmp102)
	tmp103, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.CoordinateY = float32(tmp103)
	tmp104, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.CoordinateZ = float32(tmp104)
	return err
}

/**
 * Transmission gear selection information.
 * 0 = reverse, 15 = neutral
 */
type GranTurismoTelemetry_TransmissionGear struct {
	Current uint64
	Suggested uint64
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_TransmissionGear() *GranTurismoTelemetry_TransmissionGear {
	return &GranTurismoTelemetry_TransmissionGear{
	}
}

func (this *GranTurismoTelemetry_TransmissionGear) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp105, err := this._io.ReadBitsIntLe(4)
	if err != nil {
		return err
	}
	this.Current = tmp105
	tmp106, err := this._io.ReadBitsIntLe(4)
	if err != nil {
		return err
	}
	this.Suggested = tmp106
	return err
}

/**
 * Magic file header
 * 0x30 0x53 0x37 0x47 = GT Sport and GT7
 * 0x47 0x37 0x53 0x30 = GT6
 */
type GranTurismoTelemetry_Header struct {
	Magic uint32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_Header() *GranTurismoTelemetry_Header {
	return &GranTurismoTelemetry_Header{
	}
}

func (this *GranTurismoTelemetry_Header) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp107, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Magic = uint32(tmp107)
	if !( ((this.Magic == 810760007) || (this.Magic == 1194808112)) ) {
		return kaitai.NewValidationNotAnyOfError(this.Magic, this._io, "/types/header/seq/0")
	}
	return err
}

/**
 * Gear ratios for each gear in the transmission
 */
type GranTurismoTelemetry_GearRatio struct {
	Gear []float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_GearRatio() *GranTurismoTelemetry_GearRatio {
	return &GranTurismoTelemetry_GearRatio{
	}
}

func (this *GranTurismoTelemetry_GearRatio) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	for i := 0; i < int(8); i++ {
		_ = i
		tmp108, err := this._io.ReadF4le()
		if err != nil {
			return err
		}
		this.Gear = append(this.Gear, tmp108)
	}
	return err
}

/**
 * 6DOF rotational envelope
 */
type GranTurismoTelemetry_RotationalEnvelope struct {
	Pitch float32
	Yaw float32
	Roll float32
	_io *kaitai.Stream
	_root *GranTurismoTelemetry
	_parent *GranTurismoTelemetry
}
func NewGranTurismoTelemetry_RotationalEnvelope() *GranTurismoTelemetry_RotationalEnvelope {
	return &GranTurismoTelemetry_RotationalEnvelope{
	}
}

func (this *GranTurismoTelemetry_RotationalEnvelope) Read(io *kaitai.Stream, parent *GranTurismoTelemetry, root *GranTurismoTelemetry) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp109, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Pitch = float32(tmp109)
	tmp110, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Yaw = float32(tmp110)
	tmp111, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Roll = float32(tmp111)
	return err
}
